### ISSUE TITLE
AWS Grafana share panel contains embed but this feature is not working.

### ISSUE THREAD

**Issue by yimu187** [aws/amazon-managed-grafana-roadmap#10]
Hello,

Aws grafana service has embedded report sharing feature but this feature is not functional. When this iframe is copied into an html file, aws grafana service responses x-frame-option header with deny result. You can find the response in chrome dev tools below.

Refused to display 'https://g-426a58044b.grafana-workspace.eu-central-1.amazonaws.com/' in a frame because it set 'X-Frame-Options' to 'deny'.

I checked this and this is a problem because allow_embed parameter in Grafana software is default false and it needs to be enabled by changing the grafana.ini file which can not be done with Aws Grafana at the moment.

So I suggest to add a feature to aws grafana service to enable allow_embed parameter (or the others too) in AWS Grafana service in order to have a better UX and more accurate screens.

Kind Regards
Murat YILMAZ

![image](https://user-images.githubusercontent.com/8653534/155757072-6a6afde2-d02d-4db6-9533-5dcd7c16909d.png)

**Comment by skumawat19** [comment]
Any update on this issue. Is this fixed ?

**Comment by nitrat7** [comment]
urgently need this config change!

**Comment by nfoata** [comment]
Not yet fixed, the 1st of may. I have the same issue.
Having a feature for updating the value of the Grafana settings could be great.

**Comment by ZaneL** [comment]
Please add this feature.

**Comment by 6-000-000** [comment]
Would like to see this implemented as well.

**Comment by sidfeiner** [comment]
+1 here too

**Comment by SamuelBeaurepaire** [comment]
Hello, we need it too.
@mengdic Do you have any information to share about this?

**Comment by Samobo** [comment]
Hello, we need it here too.
@mengdic Do you have any information to share on this?

**Comment by mengdic** [comment]
merge with [issue#17](https://github.com/aws/amazon-managed-grafana-roadmap/issues/17)

**Comment by beniaminmunteanu** [comment]
+1 here
