### ISSUE TITLE
Support Infinity plugin

### ISSUE THREAD

**Issue by ryanzhu2017** [aws/amazon-managed-grafana-roadmap#13]
We plan to build a proxy service between Grafana and our data base. Currently there is only a plugin data source called JSON, but it has many limitations and not well-documented. I found another plugin, called Infinity, which supports http APIs and very easy to use. It would be really convenient if we can get Infinity plugin in AMG. 
https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/

**Comment by mhausenblas** [comment]
Thanks @ryanzhu2017 and could you elaborate on the limitations a bit, please?

**Comment by ryanzhu2017** [comment]
We plan to use FastAPI in Python as our HTTP backend. I found using the current JSON data source in AMG, we have to and can only build APIs in the [existing API model](https://github.com/simPod/GrafanaJsonDatasource/blob/0.3.x/openapi.yaml). Also I cannot find an easy way to pass dashboard variables to the backend. 
With Infinity plugin, I can easily connect it with my FastAPI backend, and pass variables through both body and query params.

**Comment by samindaroshan** [comment]
As @ryanzhu2017  mentioned "JSON" plugin has  lot of restrictions.

I would be happy if you can install either "Infinity" or  "JSON API" plugin.
Both are very good plugins for retrieving API data as I have used  both of it.

Infinity
https://grafana.com/grafana/plugins/yesoreyeram-infinity-datasource/
JSON API
https://grafana.com/grafana/plugins/marcusolsson-json-datasource/

**Comment by mhausenblas** [comment]
See also #15

**Comment by VermaPriyanka** [comment]
Amazon Managed Grafana now supports discovery and installation of Grafana community plugins. Additionally, you can update the plugin version yourself in your workspace.

You would need to enable Plugin management from the Amazon Managed Grafana console, which will allow administrators in your workspace to discover, install, update and uninstall plugins.

Note that you can only install plugins from the list of plugins displayed in the [Plugin catalog](https://docs.aws.amazon.com/grafana/latest/userguide/grafana-plugins.html) in your Amazon Managed Grafana workspace.

[What's New](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-managed-grafana-community-plugins/) | [User Guide](https://docs.aws.amazon.com/grafana/latest/userguide/grafana-plugins.html) | [Blog post](https://aws.amazon.com/blogs/mt/extend-your-amazon-managed-grafana-experience-with-grafana-community-plugins/)
Refer to the announcement here - https://github.com/aws/amazon-managed-grafana-roadmap/discussions/67
