### ISSUE TITLE
Restrict access to workspace URL by CIDR range/address

### ISSUE THREAD

**Issue by williamhargrove** [aws/amazon-managed-grafana-roadmap#14]
Once an AMG workspace is provisioned the URL is open globally. I would like the ability to restrict access to this publically visable endpoint to a set of CIDR ranges/addresses, similar to the functionality offered by EC2 Security Groups.

**Comment by haarchri** [comment]
Make it configurable like EKS ControlPlane

**Comment by mengdic** [comment]
Hello Everyone, 

Today (2/16/22) Amazon Managed Grafana launch supports for network access control that helps you to restrict network access to your Grafana workspaces!

Check out the [What's New post](https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-managed-grafana-network-access-control/), [blog](https://aws.amazon.com/blogs/mt/announcing-inbound-network-access-control-in-amazon-managed-grafana/), or [user guide](https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-nac.html) on how to use VPC endpoints and customer-managed prefix lists to protect your Grafana workspace from network attacks. 

You can also [create an interface VPC endpoints](https://docs.aws.amazon.com/grafana/latest/userguide/VPC-endpoints.html) to allow AWS resources such as Amazon EC2 instances to access the Amazon Managed Grafana API to manage resources, or you can use a VPC endpoint as part of limiting network access to your Amazon Managed Grafana workspaces.

**Comment by haarchri** [comment]
@mengdic thanks for Update - we using AWS SSO for authentication If we update now to VPC Endpoint Network Protection - how we can update the automatic created AWS SSO Configuration for new VPC Endpoint ?
