### ISSUE TITLE
Plugin installation

### ISSUE THREAD

**Issue by yordaa-me** [aws/amazon-managed-grafana-roadmap#15]
As someone who uses Grafana, I would like the ability to be able to install and configure my own plugins.

I am currently interested in installing the official Sentry plugin. https://grafana.com/grafana/plugins/grafana-sentry-datasource/

**Comment by samindaroshan** [comment]
Yes, this would be a very useful functionality.

**Comment by brodster2** [comment]
This would be useful for us too. Or at least add the GitHub plugin to the list of built-in plugins
https://grafana.com/grafana/plugins/grafana-github-datasource/

**Comment by CodinMoldovanu** [comment]
+1, this would be extremely helpful.

**Comment by karl-nordstrom** [comment]
This is currently a blocker for us adopting AMG as our main dashboarding platform.

**Comment by pbegg** [comment]
We use use custom plugins and really could use this feature

**Comment by xinin** [comment]
Yes please!!!

For us it is impossible to use Managed Grafana if We can't install our own plugins.

**Comment by himallik** [comment]
I am working on SaaS transformation of product portfolio of one of the largest ISV customer. Customer developed custom plug-in to AWS managed Grafana. Customer wants to see how to add it to the product.

**Comment by endymion** [comment]
Our feasibility research has concluded that Amazon Managed Grafana will not be useful for us until we can install our own plugins.

Another show-stopper for us is that the "embed" feature for sharing a panel doesn't work with Amazon Managed Grafana.  We could work around this through plugins if we could install our own.

**Comment by romanathappymoney** [comment]
It would be handy for some plugins to make it into defaults, such as JSON API.

**Comment by KholdStare** [comment]
Any updates? This functionality would save us so much time.

**Comment by yestalgia** [comment]
We don't need custom ones, but I'd add PictureIt and Diagram to the request list. 

I would also like to know if the remaining grafana-signed plugins are going to be added.

**Comment by mwarnerdotme** [comment]
+1 for this! Especially the Grafana signed plugins.

**Comment by harrisd19** [comment]
This would also be a huge time saver for us to be able to leverage a managed Grafana instance!

**Comment by yossiv** [comment]
no custom DS or plugins, no AMG  for me.. sorry

**Comment by baxterjo** [comment]
This is the most commented on and second most upvoted issue in the roadmap and the status hasn't changed in over a year. Can we have an update @mhausenblas?

**Comment by Steinbachson** [comment]
This is definitely the main reason why we cannot fully cover our use cases with grafana. Would be great to see this soon :)

**Comment by thebearinmind** [comment]
+1, same here, please include this feature since there are a lot of data sources that are missing from defaults!

**Comment by felipefdl** [comment]
+1

**Comment by heldersepu** [comment]
Any updates on this? very interested on the Analytics Panel:
https://grafana.com/grafana/plugins/macropower-analytics-panel/

**Comment by Yunhao-Jiao** [comment]
+1 The blocker for us to onboard to AMG, at least signed plugins should be supported

**Comment by dnascimento** [comment]
+1 could you add Octopus plugin?

**Comment by jhoulihan** [comment]
> It would be handy for some plugins to make it into defaults, such as JSON API.

The functionality of [Grafana Infinity Datasource](https://sriramajeyam.com/grafana-infinity-datasource/) would be a great plugin for AMG!

**Comment by yordaa-me** [comment]
Whenever this does get picked up, it would also be great if we can choose which plugin versions we want to use.

For example. The [Amazon Athena](https://grafana.com/grafana/plugins/grafana-athena-datasource/) plugin latest version is `2.10.1` but the installed plugin version is `2.2.0`

**Comment by AdiSchwartz869** [comment]
OnCall plugin

**Comment by skylou** [comment]
+1 , Sentry Plugin

**Comment by lakshmiramteja** [comment]
OnCall plugin

**Comment by martinbruntsch** [comment]
+1, Grafana Image Renderer

**Comment by ectoskeleton** [comment]
As someone mentioned, having control over the version installed would solve lots of peoples issues.  Right now the zabbix plugin installed version is 4.2.10, which is a known problem for zabbix 6.4 and needs zabbix plugin 4.4.0 to resolve the issue.  

Is there a process to update a plugin?  There have been multiple releases since the version currently available to me?

**Comment by jschuld** [comment]
:+1, Grafana Treemap, but in general, not having the official grafana plugins available in AMG is a bit downside.

**Comment by mortiz-77** [comment]
Synthetics Monitoring and OnCall Plugin!

**Comment by ts-sean-foley** [comment]
Timepicker Buttons Panel plugin would be very useful to us.

**Comment by mhessel** [comment]
Comparison Panel plugin!

**Comment by east4ming** [comment]
+1 Plugins: Infinity

**Comment by samfenwick** [comment]
It would be super helpful if we could use the Druid Plugin https://github.com/grafadruid/druid-grafana

**Comment by VermaPriyanka** [comment]
Amazon Managed Grafana now supports discovery and installation of Grafana community plugins. Additionally, you can update the plugin version yourself in your workspace.

You would need to enable Plugin management from the Amazon Managed Grafana console, which will allow administrators in your workspace to discover, install, update and uninstall plugins.

Note that you can only install plugins from the list of plugins displayed in the [Plugin catalog](https://docs.aws.amazon.com/grafana/latest/userguide/grafana-plugins.html) in your Amazon Managed Grafana workspace.

[What's New](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-managed-grafana-community-plugins/) | [User Guide](https://docs.aws.amazon.com/grafana/latest/userguide/grafana-plugins.html) | [Blog post](https://aws.amazon.com/blogs/mt/extend-your-amazon-managed-grafana-experience-with-grafana-community-plugins/)
Refer to the announcement here - https://github.com/aws/amazon-managed-grafana-roadmap/discussions/67

**Comment by mortiz-77** [comment]
@VermaPriyanka, this is a good advancement! Yet I don't see OnCall plugin. Is this expected to be added the the plugin catalog?

**Comment by VermaPriyanka** [comment]
@michael-ortiz Plugins that require additional configurations/dependencies or more validation are still not in the catalog, and will be evaluated before getting added to the catalog.

**Comment by dana-Navee** [comment]
Hello @VermaPriyanka , Grafana Image Renderer seems to still be not on the list , though its Grafanalab based and very useful plugin , any idea if there are plans to include it any time soon ?

**Comment by rcosperec** [comment]
Yeah, Grafana Image Renderer really is an addition the AGM userbase is looking for.

**Comment by VermaPriyanka** [comment]
@dana-Navee @sk5-rcosperec Grafana Image Renderer is definitely a useful plugin. Please share your use-cases that you would like to address with this plugin.

**Comment by SoftwareHPT** [comment]
Hi @VermaPriyanka, do you know if there is any interest in the support of the Video plugin by Innius? My team is trying to develop a dashboard that can display metrics about a product being tested and a real-time video of the product being tested. It would help us showcase current progress to clients in one complete package, thanks.

**Comment by dana-Navee** [comment]
Hey @VermaPriyanka , we need it to do integration reporting between grafana and other tools we use. (Image Notification)

For example we want to schedule sending a specific panel screenshot daily to a slack chanel (to report numbers , etc)  and "Grafana Image Renderer" helps in achieving that.

**Comment by rcosperec** [comment]
Hello @VermaPriyanka ! 

Pretty much the same use case as already described, this plugin is mainly used when integrating Grafana alerts to slack, discord or else.

It gives a quick, precise and visual information to whoever is OnCall when alerts arise. 

Having the image of the latest data allows to skip the step where the person in charge has to go check on Grafana directly to know what's up and jump right on addressing the issue.

Right now classical alerts are the only one who are usable for such purpose, but I believe the support for this plugin is another step in improving the alerting capabilities of Grafana Managed, alongside the work on unified alerting.

**Comment by mortiz-77** [comment]
+1 for Image Renderer. We need this as well!

**Comment by Murat-on-github** [comment]
I really need Bubble chart plug in to make use of Graphana. It is not available for AMG
https://grafana.com/grafana/plugins/digrich-bubblechart-panel/?tab=overview

**Comment by ilkerispir** [comment]
[Image renderer](https://grafana.com/grafana/plugins/grafana-image-renderer/) plugin needs to be added by default.

**Comment by VermaPriyanka** [comment]
Thanks all for the inputs. Grafana image renderer request has a Github issue of it's own: https://github.com/aws/amazon-managed-grafana-roadmap/issues/5. Will close this one, so individual plugin requests can be tracked separately.
The revised Bubble chart version is v10 compatible, we can track this request as a part for v10 requested features.

**Comment by VermaPriyanka** [comment]
Thanks all for the inputs. Grafana image renderer request has a Github issue of it's own: https://github.com/aws/amazon-managed-grafana-roadmap/issues/5. Will close this one, so individual plugin requests can be tracked separately.
The revised Bubble chart version is v10 compatible, we can track this request as a part for v10 requested features.
