### ISSUE TITLE
Add RDS as a data source

### ISSUE THREAD

**Issue by sobi3ch** [aws/amazon-managed-grafana-roadmap#19]
I need to add our RDS Postgres as a data source and don't see any way to do it.

I assume this could be done with RDS data source or maybe VPC Endpoint

Current data sources:
- AWS IoT SiteWise	
- AWS X-Ray	
- Amazon CloudWatch	
- Amazon OpenSearch Service	
- Amazon Managed Service for Prometheus	
- Amazon TimeStream	
- Amazon Redshift	
- Amazon Athena

I found only this post which suggest you are working on it..
https://repost.aws/questions/QUv9XVkV6YRtSOgGcWisHhYg/is-there-an-ip-block-for-whitelisting

**Comment by Larzack** [comment]
Add RDS please

**Comment by vipulvv** [comment]
Any updates on this? I couldn't find any documented approach getting RDS Postgres work as a data source.
The Managed Grafana couldn't reach RDS postgres, even with a VPC endpoint & SG.

**Comment by yestalgia** [comment]
Same problem here - Any updates?

**Comment by haarchri** [comment]
We also need this feature

**Comment by emretoptanci** [comment]
There is no RDS data source but there are built-in data sources for Postgres, MySQL, and MSSQL.
Why don't you use those?

**Comment by haarchri** [comment]
Then you need to open your RDS to the Internet because Grafana is unable to reach private vpc adresses

**Comment by emretoptanci** [comment]
> Then you need to open your RDS to the Internet because Grafana is unable to reach private vpc adresses

Yes. Makes sense. And I can say that it is not limited to databases. There can be many other things in a VPC that I would like to use as a data source. 

It would be best if we could connect Grafana to a VPC via a tunnel. I think #26 requests this.

**Comment by haarchri** [comment]
looks like AWS releases it https://aws.amazon.com/de/blogs/mt/announcing-private-vpc-data-source-support-for-amazon-managed-grafana/

**Comment by mengdic** [comment]
Hello All, The Amazon Managed Grafana team has launched support for VPC connections with your Amazon Managed Grafana workspaces 🚀 So you can now connect to your RDS to Amazon Managed Grafana workspace! 

Learn more from:
- [What’s New Post](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-managed-grafana-connection-data-sources-hosted-virtual-private-cloud/)
- [Blog](https://aws.amazon.com/blogs/mt/announcing-private-vpc-data-source-support-for-amazon-managed-grafana/)
- [User Guide](https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-vpc.html)

We are also actively collecting user feedback and use cases. If you have any requests or questions regarding the VPC connection feature in Amazon Managed Grafana, feel free to leave a comment here.
