### ISSUE TITLE
Support AWS/AppRunner namespace

### ISSUE THREAD

**Issue by drusellers** [aws/amazon-managed-grafana-roadmap#20]
I was just setting up Grafana and looking to add a variety of metrics coming out of AppRunner but I don't see it in the list of "Namespaces" supported.

![CleanShot 2022-06-15 at 12 24 47@2x](https://user-images.githubusercontent.com/63355/173888413-30e7f476-cb78-474a-9b11-95f6357bfb24.png)

I would love to utilize AppRunner and see my metrics in this dashboard.

**Comment by yimipeng** [comment]
Thanks for the reaching out and interested in App Runner. Today, we do support [CloudWatch metrics](https://docs.aws.amazon.com/apprunner/latest/dg/monitor-cw.html) in the `AWS/AppRunner` namespace. Not sure there is additional integration needed for Amazon Managed Grafana to get it. We will take a look and keep you posted. 
Besides, if there is any feature request or question about App Runner. Please kindly do not hesitate to cut an issue in https://github.com/aws/apprunner-roadmap/issues

Thanks.

**Comment by VermaPriyanka** [comment]
`AWS/AppRunner `is now listed in the list of namespaces for Amazon Managed Grafana workspaces running v9.4. Also, if you find any missing namespace, you can still query metrics from the same, by adding the namespace to `Namespaces of Custom metrics` to the data source config page. The metrics won't show up in the list of metrics, but you can type them in to query the same. 
As a long term solution, we want this list to be updated dynamically, so you can see all newly added namespaces as soon as they get added to Cloudwatch.
