### ISSUE TITLE
Grafana VPC endpoint

### ISSUE THREAD

**Issue by barthel** [aws/amazon-managed-grafana-roadmap#26]
In my organization, services that are only publicly accessible are not welcome and cause additional configuration effort or simply do not work with other services that are only accessible via the VPC.

We (urgently) need the ability to include Grafana with a VPC endpoint to allow access to (for example) AWS OpenSearch (with VPC endpoint).
In combination with the support of Custom Domains (#6) the implementation should work similar to AWS OpenSearch.

**Comment by barthel** [comment]
@mahmoud-hafez-aws

**Comment by barthel** [comment]
@mhausenblas, @mahmoud-hafez-aws  Combined with #6, this issue becomes a blocker in our organization.

**Comment by haarchri** [comment]
Checkout: https://aws.amazon.com/de/blogs/mt/announcing-private-vpc-data-source-support-for-amazon-managed-grafana/

**Comment by mengdic** [comment]
Hello All, The Amazon Managed Grafana team has launched support for VPC connections with your Amazon Managed Grafana workspaces 🚀 

Learn more from: 
- [What’s New Post](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-managed-grafana-connection-data-sources-hosted-virtual-private-cloud/) 
- [Blog](https://aws.amazon.com/blogs/mt/announcing-private-vpc-data-source-support-for-amazon-managed-grafana/)
- [User Guide](https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-vpc.html)

We are also actively collecting user feedback and use cases. If you have any requests or questions regarding the VPC connection feature in Amazon Managed Grafana, feel free to leave a comment here.

**Comment by mengdic** [comment]
Hello All, we expanded the support for Amazon Managed Grafana support for VPC connections in LHR (eu-west-2) and SIN (ap-southeast-1) regions as well upon customers' requests 🚀

**Comment by mengdic** [comment]
Hello Everyone, 

Today (2/16/22) Amazon Managed Grafana launch supports for network access control that helps you to restrict network access to your Grafana workspaces!

Check out the [What's New post](https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-managed-grafana-network-access-control/), [blog](https://aws.amazon.com/blogs/mt/announcing-inbound-network-access-control-in-amazon-managed-grafana/), or [user guide](https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-nac.html) on how to use VPC endpoints and customer-managed prefix lists to protect your Grafana workspace from network attacks. 

You can also [create an interface VPC endpoints](https://docs.aws.amazon.com/grafana/latest/userguide/VPC-endpoints.html) to allow AWS resources such as Amazon EC2 instances to access the Amazon Managed Grafana API to manage resources, or you can use a VPC endpoint as part of limiting network access to your Amazon Managed Grafana workspaces.  🚀

**Comment by Byeong-jun-Kim** [comment]
Hello @mengdic ,

May I know the schedule for supporting the vpc connection for the Seoul region(ap-northeast-2)?

**Comment by MaGaudin** [comment]
Hi there. But is it possibile to access Managed Grafana Console from the On-premises through direct connect and so VPC Endpoints? I'm getting "Not Found" error.
Any idea?

**Comment by weiwarren** [comment]
the endpoint is not the same as workspace url
