### ISSUE TITLE
Update Amazon Timestream datasource plugin to >= v2.1.0

### ISSUE THREAD

**Issue by hgs847825** [aws/amazon-managed-grafana-roadmap#27]
In ap-northeast-1 (Tokyo), Amazon Timestream is already launched, but Amazon Timestream datasource plugin (currently v1.5.2) is not support ap-northeast-1.
ap-northeast-1 is supported on Amazon Timestream datasource plugin v.2.1.0.
For this reason, Amazon managed grafana and Amazon Timestream is not work in ap-northeast-1.
Do you have any concrete plans to update the plugin?

**Comment by VermaPriyanka** [comment]
Amazon Timestream plugin is at v2.30 now in Amazon Managed Grafana.
