### ISSUE TITLE
Managed Grafana CDK support

### ISSUE THREAD

**Issue by ethiebautgeorge-nasuni** [aws/amazon-managed-grafana-roadmap#29]
There is currently no support in the CDK to deploy Managed Grafana.
Would it be possible to add official support in the CDK so that we can automate the deployment of Managed Grafana as part of our solution?

Thanks!

**Comment by VermaPriyanka** [comment]
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_grafana-readme.html
