### ISSUE TITLE
AWS CloudFormation support for control plane APIs

### ISSUE THREAD

**Issue by mhausenblas** [aws/amazon-managed-grafana-roadmap#3]
Currently, Amazon Managed Grafana supports [data plane automation via Terraform](https://aws-observability.github.io/aws-o11y-recipes/recipes/amg-automation-tf/), such as for creating data sources or dashboards. 

We plan to launch AWS CloudFormation support for Amazon Managed Grafana control plane APIs such as for creating, deleting, and upgrading workspaces and with this feature help increasing end-to-end automation around managing and operating Amazon Managed Grafana workspaces.

**Comment by iainhtp** [comment]
We too would like to see the ability to create Amazon Managed Grafana Workspaces via aws cli / terraform

**Comment by fredriv** [comment]
Terraform supports creating Amazon Managed Grafana workspaces since AWS provider v4.2.0: https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#420-february-18-2022

Docs for the Terraform resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_workspace

**Comment by williamhargrove** [comment]
I would like to add a thumbs up for Cloudformation support and I have been told this is on the roadmap with some delivery dates in the nearterm? Is it possible to publish some update on when this might be delivered?  Thanks.

**Comment by rene84** [comment]
We are very much interested in using managed grafana, but not having cloudformation is a non-starter for us. Any comments on the priority?

**Comment by mengdic** [comment]
Hello Everyone,  

Today (12/09/22) [Amazon Managed Grafana launched the support for AWS CloudFormation](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-managed-grafana-support-aws-cloudformation). 

You can now use AWS CloudFormation templates to create, update, and delete your Amazon Managed Grafana workspaces, as well as manage or update workspace SAML authentication settings. You can use templates to provision new Grafana workspaces, edit workspace settings such as workspace name or description, and manage the lifecycle of your Grafana workspaces programmatically. You can also create CloudFormation templates to configure workspace authentication options such as setting up SAML Identity Providers, specifying user roles, or defining attributes to identify user authentication. 

To learn more about manage Amazon Managed Grafana workspaces and configuring workspace SAML authentication with CloudFormation, see the [Amazon Managed Grafana resource type reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Grafana.html) in the CloudFormation user guide. To create Amazon Managed Grafana workspaces using AWS CloudFormation, follow the [reference templates](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-grafana-workspace.html#aws-resource-grafana-workspace--examples).

Feel free to leave a comment if you have any questions. We are actively collecting user feedback and use cases.

**Comment by mengdic** [comment]
Hello Everyone, 

Today (2/16/22) Amazon Managed Grafana launch supports for network access control that helps you to restrict network access to your Grafana workspaces!

Check out the [What's New post](https://aws.amazon.com/about-aws/whats-new/2023/02/amazon-managed-grafana-network-access-control/), [blog](https://aws.amazon.com/blogs/mt/announcing-inbound-network-access-control-in-amazon-managed-grafana/), or [user guide](https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-nac.html) on how to use VPC endpoints and customer-managed prefix lists to protect your Grafana workspace from network attacks. 

You can also [create an interface VPC endpoints](https://docs.aws.amazon.com/grafana/latest/userguide/VPC-endpoints.html) to allow AWS resources such as Amazon EC2 instances to access the Amazon Managed Grafana API to manage resources, or you can use a VPC endpoint as part of limiting network access to your Amazon Managed Grafana workspaces.

**Comment by RobKenis** [comment]
@mengdic What is the plan for managing data sources and dashboards through CloudFormation?

**Comment by rpractice** [comment]
Hi @mengdic , Any updated on managing Grafana dashboards, data sources using Cloudformation, because its been almost an year now.
