### ISSUE TITLE
Support Button Panel

### ISSUE THREAD

**Issue by raffistef** [aws/amazon-managed-grafana-roadmap#31]
Currently there is no button panel.
It would very useful to be able to add a button directly into our dashboard.
For isntance a click on the button will call a lambda that execute some tasts.
https://grafana.com/grafana/plugins/cloudspout-button-panel/

**Comment by Yunhao-Jiao** [comment]
+1 this is a very critical feature for us

**Comment by AlxndrJhn** [comment]
looks like it is still not supported.

use-case: allow API calls from a dashboard

**Comment by VermaPriyanka** [comment]
This plugin is deprecated and no longer maintained. Have you tried the Button plugin (https://github.com/speakyourcode/grafana-button-panel) , Amazon Managed Grafana allows to install once you have Plugin Management enabled.
