### ISSUE TITLE
Support Loki Live Tailing

### ISSUE THREAD

**Issue by bibli-alex** [aws/amazon-managed-grafana-roadmap#34]
I have received communication from internal AWS support teams stating that Live Tailing with Loki is not supported. 

[The documentation](https://docs.aws.amazon.com/grafana/latest/userguide/using-loki-in-AMG.html) says otherwise.

I would like to request that live tailing be officially supported, and that the documentation is changed in the meantime to be explicit that this feature is _not_ supported currently.

**Comment by mengdic** [comment]
Hi @bibli-alex thank you for submitting the request. 
The documentation has been updated, apologize for the confusion.

**Comment by aristosvo** [comment]
@mengdic Can you provide insight whether this feature is on the roadmap and/or available yet?

I have trouble getting it to work: `Live tailing was stopped due to following error: undefined`

The documentation does not contain explicit information about this feature being available or not.
