### ISSUE TITLE
How to install signed plugins in AWS managed grafana

### ISSUE THREAD

**Issue by saumilsdk** [aws/amazon-managed-grafana-roadmap#36]
How to install signed plugins in AWS managed grafana

**Comment by heldersepu** [comment]
Looks like a duplicate of https://github.com/aws/amazon-managed-grafana-roadmap/issues/15

**Comment by VermaPriyanka** [comment]
Refer to this announcement: https://github.com/aws/amazon-managed-grafana-roadmap/discussions/67
