### ISSUE TITLE
Update version of Github Plugin (1.0.14 (installed version))

### ISSUE THREAD

**Issue by gabrielbac** [aws/amazon-managed-grafana-roadmap#37]
1.0.14  version has an issue with queries not supporting variables,

See:
https://github.com/grafana/github-datasource/issues/166

It would be great if it can be updated to the latest version

**Comment by VermaPriyanka** [comment]
@gabrielbac Amazon Managed Grafana now supports discovery and installation of Grafana community plugins. Additionally, you can update the plugin version yourself in your workspace.

You would need to enable Plugin management from the Amazon Managed Grafana console, which will allow administrators in your workspace to discover, install, update and uninstall plugins.

[What's New](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-managed-grafana-community-plugins/) | [User Guide](https://docs.aws.amazon.com/grafana/latest/userguide/grafana-plugins.html) | [Blog post](https://aws.amazon.com/blogs/mt/extend-your-amazon-managed-grafana-experience-with-grafana-community-plugins/)
Refer to the announcement here - https://github.com/aws/amazon-managed-grafana-roadmap/discussions/67
