### ISSUE TITLE
Add AWS Data Source 504

### ISSUE THREAD

**Issue by alibner** [aws/amazon-managed-grafana-roadmap#38]
When I configured the AWS managed prometheus data source from Grafana, the message was always fetching data, and then an error 504 was reported, similar to https://repost.aws/questions/QUNggPmSMNRDuxYoxXdEocYg/unable-to-connect-aws-managed-grafana-service-to-private-rds-instance.

**Comment by Oliver-ke** [comment]
I'm getting this same error while trying to connect Cloudwatch data source 
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/32667315/221491212-56ae4007-bed6-4479-957f-d814a12577a6.png">

**Comment by boserup** [comment]
Make sure you connect to the VPC interface endpoint and any applied security groups does not block access.
https://docs.aws.amazon.com/grafana/latest/userguide/VPC-endpoints.html

**Comment by mengdic** [comment]
Hi folks, please send us a support ticket via AWS support so we can check on the errors from your workspace.

**Comment by maymayman** [comment]
@Oliver-ke Did you have any solution for your issue?

**Comment by CumpsD** [comment]
I have a Grafana VPC endpoint set up, but still getting this :(

**Comment by CumpsD** [comment]
Ok, so the required endpoint is `com.amazonaws.eu-west-1.aps` to solve this

**Comment by vineetguptadev** [comment]
@CumpsD Where exactly did you enter this endpoint ?
