### ISSUE TITLE
Please allow additional visualization plugins to be installed

### ISSUE THREAD

**Issue by rsheldon-sincro** [aws/amazon-managed-grafana-roadmap#42]
There are a lot of visualization plugins available for grafana, and AMG provide only a few of them. I understand that you want to provide a curated set of functionality, but the UI plugins run on the client side, so I an admin installs a plugin that has issues, that's on them.

For example, some of the ones I think are useful:

- Treemap Panel - https://grafana.com/grafana/plugins/marcusolsson-treemap-panel/
- Polystat Panel - https://grafana.com/grafana/plugins/grafana-polystat-panel/
- Bubble Chart - https://grafana.com/grafana/plugins/digrich-bubblechart-panel/
- https://grafana.com/grafana/plugins/jdbranham-diagram-panel/

**Comment by heldersepu** [comment]
Looks like a duplicate of #15

**Comment by rsheldon-sincro** [comment]
Yup, my bad, it's a dupe of #15.

**Comment by VermaPriyanka** [comment]
Refer to this announcement: https://github.com/aws/amazon-managed-grafana-roadmap/discussions/67
