### ISSUE TITLE
Feature Flag support

### ISSUE THREAD

**Issue by gravitylow** [aws/amazon-managed-grafana-roadmap#44]
AMG lacks the ability to enable a feature flag: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#feature_toggles

Which is in turn blocking the ability to use cross-account observability in the CloudWatch datasource: https://github.com/grafana/grafana/blob/254577ba568d8010dcc96446e788866d618c96c8/docs/sources/datasources/aws-cloudwatch/query-editor/index.md#cross-account-observability

Which is a blocker for us to use AMG

**Comment by mengdic** [comment]
Hi @gravitylow cross-account in CloudWatch data source is supported in AMG today. Please check out our [user documentation](https://docs.aws.amazon.com/grafana/latest/userguide/cloudwatch-cross-account.html) and [blog post](https://aws.amazon.com/blogs/opensource/setting-up-amazon-managed-grafana-cross-account-data-source-using-customer-managed-iam-roles/) for guides on how to set it up. If you have further question, please send us a support ticket so we can check on your workspace and IAM permission setup.
