### ISSUE TITLE
No internet access in VPC

### ISSUE THREAD

**Issue by AndreLacasse** [aws/amazon-managed-grafana-roadmap#49]
**Version:** Grafana 9.4

**Problem:**

I cannot use Github Data source or JSON endpoint on AWS Grafana in public VPC, the Health check failed. The same Data Source work fine in Grafana outside of a VPC.

**Step to reproduce**

- **Create a VPC and more**
- Number of availability zone **2**
- Number of public subnet **2**
- Number of private subnet **0**
- NAT gateway **None**
- Enable DNS hostname
- Enable DNS resolution
- **Create Grafana instance**
- VPC from previous step
- Use both public subnet
- Use Default security group
- Choose Open Access
- Add Github Data source and test.

**Comment by mengdic** [comment]
Hi @AndreLacasse , please create a support ticket and we will check on it asap. Thanks.

**Comment by AndreLacasse** [comment]
My support plan is basic, so I cannot create technical support ticket.
