### ISSUE TITLE
Your Insight Needed: What are you looking for in version 10+?

### ISSUE THREAD

**Issue by mengdic** [aws/amazon-managed-grafana-roadmap#51]
Hello Amazon Managed Grafana community,

As many of you might know, Grafana 10 was announced in GrafanaCon on 6/13. As the Amazon Managed Grafana services, we actively listen to the community’s asks and would like to push for the new version support along the way continuously. To help us shape the Amazon Managed Grafana service to fit your use case, we invite you to answer the following questions about Grafana 10:

**1. What features do you consider a 'must-have' for Grafana 10?** 
We want to know what critical functions you require to accomplish your tasks and meet your goals. Please tell us about your specific use case; this context will help us understand the full scope of your needs.

**2. What features would you consider a 'nice-to-have' for Grafana 10?** 
These features improve your Amazon Managed Grafana experience, even if they aren't critical for your work. Again, providing a use case here would help us understand how such a feature might be helpful to you and others in the community.

**3. Any other feedback you would like to share since we introduced the self-service version control in Amazon Managed Grafana?** 

To participate in this feedback collection, please reply directly to this thread. Alternatively, if you prefer a more private channel, feel free to direct message us or send your responses via email to [aws-grafana-feedback@amazon.com](mailto:aws-grafana-feedback@amazon.com).

Your input has the potential to make a significant impact on the functionality, usability, and prioritization of our roadmap. Thank you for your time, insights, and support in helping us continuously improve the Amazon Managed Gafana. 

Best regards,
Mengdi Chen
Sr. Technical Product Manager, Amazon Managed Grafana

**Comment by Steinbachson** [comment]
Hi mengdic,

thanks for opening this issue.

1. Grafana 10 offers with "Trends" and "XY Chart" new visualization which allow users for the first time to select a different value than time for x-axis.  An expert talk with GrafanaLabs showed that there is no other option for that using currently available visualization types. So this is a "Must-have" for many use cases me and the community have.  One of my use cases is to analyze technical measurement data where time plays an a subordinate role (e.g. engine power and engine torque) or where I want to have a look at the time duration but not on the absolute time range. An example of the visualization type "Trend" from Grafana 10 where time duration as x-axes is used you can see here:

![Grafana_Visualization_Trend_x-Axes_TimeDuration_anonym](https://github.com/aws/amazon-managed-grafana-roadmap/assets/46324342/f7765473-e23a-4d91-8d54-4d457b826e39)

Another "Must-have" but which is not connected only to version 10 is the reporting function. Having the chance to export dashboards as PDF to map the entire data analysis process is the reason why we still need to use Grafana Cloud Pro. Since this is another seperate cloud application which is not approved by the IT-departement of many of our potential customers, this feature holds us back to make business with them.

2. A "Nice-to-have" for me are Subfolders. There are many developers with editor-role in our workspace who build their individual dashboards based on a dashboard which is used for productive work. At the moment there is a folder for each developer where they collect their individual dashboards. Many of these individual dashboards tackle similar questions and use cases since they are also based on the same dashboard-template. Being able to sort them not only by developer but also by use case would increase the collaboration between the developers. This would be possible if we had the chance to build e.g. folders for use cases where one subfolder for each developer would be inside.

Thanks for checking these wishes with your roadmap, I really appreciate that!
Cheers, David

**Comment by rpractice** [comment]
Hi @mengdic ,
One of the must-have features would be to have a Microsoft teams integration as I have seen a lot of other users facing the problem of using SNS which does not trigger notifications properly.

**Comment by garett-eiq** [comment]
A must-have feature for us is surfacing a way to control [feature toggles](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/). Right now this is preventing us from using cross-account metrics observability from a single monitoring account. This is a super-critical item for us, and is forcing us to consider moving to self-managed Grafana

**Comment by martinbruntsch** [comment]
Hi @mengdic 
I think the Image Renderer is overdue ..and therefore a must-have in order to equip alerts with images ->https://github.com/aws/amazon-managed-grafana-roadmap/issues/5 
cheers

**Comment by cnocula-peg** [comment]
> Hi @mengdic , One of the must-have features would be to have a Microsoft teams integration as I have seen a lot of other users facing the problem of using SNS which does not trigger notifications properly.

See: https://github.com/aws/amazon-managed-grafana-roadmap/issues/18

**Comment by noutn** [comment]
Hi @mengdic,
The must have feature that I am missing in the current version of Grafana is the 'disconnect value' option in the State Timeline panel. I cannot find a different good way to visualize state values, which sometimes have NULL values and sometimes have missing values.
Cheers.

**Comment by niroz89** [comment]
Hi @mengdic 
* We would like to have the option to have a single workspace with multiple organizations. https://github.com/aws/amazon-managed-grafana-roadmap/issues/25

**Comment by janeshchhabra** [comment]
We've been asking for image renderer and custom plugin for years. Please prioritize that. Otherwise at this point, there is nearly no reason to use AMG. It's useless compared to Grafana itself which has these features out of the box.

**Comment by FredStober** [comment]
I think this is a must have: https://github.com/aws/amazon-managed-grafana-roadmap/issues/16

Right now it's incredibly hard to prevent data leakages even with SSO enabled, since sharing a snapshot grants access even to unauthenticated users.

**Comment by rafaelzacarias** [comment]
It would be great to see the interactive button feature from [Grafana v10.2](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-2/#create-interactive-buttons-in-canvas-visualizations) in AWS Grafana.
 It could turn Grafana into a powerful control panel.

**Comment by atze234** [comment]
It would be great to have 10.2, especially the Provisioned Alert Export Function: https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-2/#export-alerting-resources-to-terraform

**Comment by raymalt** [comment]
It would be great to have 10.2, since we're using the Transform feature "Config from query results". Version 9 seems to be lacking the possibility to use several queries for this transform to control different gauges.

**Comment by andonovrnd** [comment]
- enabling disabling the provenance header which is responsible for the editing the alerts which are from the provisioned state : https://github.com/grafana/terraform-provider-grafana/issues/845
- hoping that the v10 would come with a fixed deduplication of the alerting https://github.com/aws/amazon-managed-grafana-roadmap/issues/47

**Comment by radevkal** [comment]
The most imporant feature our Organization is waiting for is support of  Grafana Scenes and Private data sourcesVersion Grafana Scenes Frontend Libary would simplify Dashboard automation for us. 
We also need Private DataSource support to centralize observability infrastructure.

**Comment by MaGaudin** [comment]
Hi,

could be good to have the Correlation feature (https://grafana.com/docs/grafana/latest/administration/correlations/).  but... when we will have version 10 for managed grafana?

**Comment by mesparks** [comment]
My thoughts:
* Trend Engine
* Time Regions
* Public Dashboards
* Multiple methods of authentications, right now we need to share some dashboards with a customer of ours and we can't because we use SSO and can't define local users in grafana

**Comment by EAlf91** [comment]
**must-have**
Using the Canvas Plugin is unfortunately not possible as it's not possible to load any image from any url. This would be highly appreciated and related to #5 otherwise AMG is unusable for due to branding requirements from our clients

**Comment by cgalatoulas** [comment]
- Fixing the https://github.com/aws/amazon-managed-grafana-roadmap/issues/47 bug. Makes it almost unusable.

**Comment by derekleegh** [comment]
- Dashboard export to PDF. This functionality should be available not only on the Enteprise licensing.
- Email Reporting function to schedule and send dashboard as pdf to target executives. 
- Update geomap functionality support

**Comment by lorrrrrrrenzo** [comment]
Support for live tailing CloudWatch Logs. 

https://github.com/grafana/grafana/issues/83200

**Comment by pk-hugo** [comment]
Support to enable the Grafana On Call plugin and the other IRM features of Grafana would be a good addition.

**Comment by r-lindner** [comment]
Grafana 10 has many great additions but currently the [Interactive Tree Panel](https://grafana.com/grafana/plugins/equansdatahub-tree-panel/) plugin (needs grafana &ge; 10.0) would be great.

**Comment by VermaPriyanka** [comment]
> A must-have feature for us is surfacing a way to control [feature toggles](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/). Right now this is preventing us from using cross-account metrics observability from a single monitoring account. This is a super-critical item for us, and is forcing us to consider moving to self-managed Grafana

Are you referring to Cloudwatch cross-account metrics? If yes, this is enabled by default in Amazon Managed Grafana

**Comment by edhgoose** [comment]
Expanding the Contact Types is a must have for us - in particular the webhook one. I was really surprised to find the Managed contact types are significantly limited.

**Comment by ri-roee** [comment]
@mengdic is there an ETA for `10.x` ?

**Comment by tyler-hc** [comment]
It seems we need nested folders to migrate over to Amazon Managed Grafana. Our self-hosted setup is using those and there's no way for me to manage AMG with the grafana terraform provider due to that.

**Comment by whiteninja76** [comment]
All the alerting improvements that come with version 10.  especially the point  andonovrnd mentioned.

> * enabling disabling the provenance header which is responsible for the editing the alerts which are from the provisioned state : [Issue providing X-Disable-Provenance header grafana/terraform-provider-grafana#845](https://github.com/grafana/terraform-provider-grafana/issues/845)
> * hoping that the v10 would come with a fixed deduplication of the alerting [Notification deduplication for Unified Alerting #47](https://github.com/aws/amazon-managed-grafana-roadmap/issues/47)

Is there a estimated timeframe when a version 10 upgrade might be possible?

**Comment by AdiSchwartz869** [comment]
Silences: The capability to suppress alerts when utilizing Grafana Alert Manager.
Microsoft Teams Integration: Seamless integration of Grafana contact points with Microsoft Teams.
Customization Options: The option to differentiate between various workspaces/environments by incorporating a logo, name header, or DNS.

**Comment by VermaPriyanka** [comment]
Amazon Managed Grafana now supports Grafana version 10.4. See this [announcement](https://github.com/aws/amazon-managed-grafana-roadmap/discussions/74) for more details.

**Comment by cnocula-peg** [comment]
For all of those, who are urgently waiting for integration to MS Teams, still nothing.. 

![image](https://github.com/aws/amazon-managed-grafana-roadmap/assets/91733677/da1450a1-ed55-480c-8462-bf4ca9d92c00)

![image](https://github.com/aws/amazon-managed-grafana-roadmap/assets/91733677/00777af1-1426-489a-ba7a-b03f9241afeb)

**Comment by volphy** [comment]
Not an out-of-box solution but AWS ChatBot is capable of sending notifications to MS Teams:
https://aws.amazon.com/chatbot/

**Comment by VermaPriyanka** [comment]
We understand that many requests shared here aren't addressed with the v10 release in Amazon Managed Grafana. including Reporting, Teams integration, Organizations support. We are tracking these as independent feature requests with the MS teams integration request being tracked here: https://github.com/aws/amazon-managed-grafana-roadmap/issues/18.

**Comment by ahsanejazzz** [comment]
Notifications are sent 3x and there is no support for Email or MS teams integration in contact points. The notification template does nothing. Thanks for "Amazon RUINED Grafana"

**Comment by darrenhorwitz1-was-taken** [comment]
Amazon , wtf , this issue has been closed and you have the worst product in terms of features. There are so many features that are missing from your grafana on the versions you have decided to support . Like why is there no webhook support ... this has been on grafana pre v10 . please release v11 asap
