### ISSUE TITLE
BUG: Missing Authentication token

### ISSUE THREAD

**Issue by stijndehaes** [aws/amazon-managed-grafana-roadmap#61]
Somewhere today we noticed that our connection to aws managed prometheus in managed grafana is not working anymore. We always get a Missing Authentication Token pop up:

![Screenshot 2023-08-30 at 14 13 08](https://github.com/aws/amazon-managed-grafana-roadmap/assets/5019818/91f9a50b-6850-42a7-894a-c95feea84989)

We have not changed our configuration so I do not know what is going on

**Comment by stijndehaes** [comment]
never mind, something changed in our config I figured out the issue

**Comment by dabcoder** [comment]
@stijndehaes Care to share what your configuration issue was more specifically?

**Comment by szl0144** [comment]
Same issue here, would like to know how to resolve
