### ISSUE TITLE
Update to 10.1+

### ISSUE THREAD

**Issue by Travis-VelloxGroup** [aws/amazon-managed-grafana-roadmap#62]
Grafana has had another major version release, and is now on 10.1, can we get an indicative time when this upgrade will be available?

**Comment by mengdic** [comment]
Hi @Travis-Spidertracks thank you for raise the request. We are currently gathering the use case to evaluate the v10+, would you mind comment in [this issue ](https://github.com/aws/amazon-managed-grafana-roadmap/issues/51)and share more details on your use case?
