### ISSUE TITLE
Update simpod-json-datasource plugin to >= 0.6.0

### ISSUE THREAD

**Issue by mpierrau** [aws/amazon-managed-grafana-roadmap#63]
Hi,

Any plans on supporting a newer version of the [json-simpod-datasource](https://grafana.com/grafana/plugins/simpod-json-datasource/) plugin in the upcoming updates? The current plugin is version `0.5.0`, whereas the latest version is `0.6.3`. This would be much appreciated as there is a breaking change in `0.6.0`!

**Comment by VermaPriyanka** [comment]
@mpierrau Amazon Managed Grafana now supports discovery and installation of Grafana community plugins. Additionally, you can update the plugin version yourself in your workspace.

You would need to enable Plugin management from the Amazon Managed Grafana console, which will allow administrators in your workspace to discover, install, update and uninstall plugins.

[What's New](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-managed-grafana-community-plugins/) | [User Guide](https://docs.aws.amazon.com/grafana/latest/userguide/grafana-plugins.html) | [Blog post](https://aws.amazon.com/blogs/mt/extend-your-amazon-managed-grafana-experience-with-grafana-community-plugins/)
Refer to the announcement here - https://github.com/aws/amazon-managed-grafana-roadmap/discussions/67
