### ISSUE TITLE
Pyroscope supports?

### ISSUE THREAD

**Issue by gavin-jeong** [aws/amazon-managed-grafana-roadmap#64]
Seems there are no option to use Phlare / Pyroscope for now.
Any plan or schedule to support this?

**Comment by VermaPriyanka** [comment]
Pyroscope is a native plugin with Grafana v10: https://grafana.com/grafana/plugins/grafana-pyroscope-datasource/
v10 release discussion/inputs are being tracked in https://github.com/aws/amazon-managed-grafana-roadmap/issues/51

**Comment by VermaPriyanka** [comment]
Amazon Managed Grafana now supports Grafana version 10, which adds Grafana Pyroscope as a core plugin. See this [announcement](https://github.com/aws/amazon-managed-grafana-roadmap/discussions/74) for more details.
