### ISSUE TITLE
Exporting of data

### ISSUE THREAD

**Issue by ZeroDeltaAlpha** [aws/amazon-managed-grafana-roadmap#7]
Allow the managed grafana service to export dashboards and other config either just as a download zipped up or to s3 for portability.

**Comment by mhausenblas** [comment]
Hey @ZeroDeltaAlpha thanks a lot for the suggestion and I'm wondering what exactly it is you're looking for beyond what you can do already today using the [Grafana APIs](https://docs.aws.amazon.com/grafana/latest/userguide/Using-Grafana-APIs.html) we expose, incl. the Dashboard and Snapshot APIs?

**Comment by ZeroDeltaAlpha** [comment]
Hi @mhausenblas I think if the current AWS API would allow you to move between a self hosted grafana and the AWS hosted version that is sufficient.

**Comment by mhausenblas** [comment]
@ZeroDeltaAlpha thanks and that is indeed possible already, hence I'm wondering what, in addition you're looking for, if that makes sense? :)

**Comment by ZeroDeltaAlpha** [comment]
@mhausenblas  Closing this as I am happy to know that this is possible. Many thanks for your time explaining this.
