### ISSUE TITLE
Grafana 9.5 upgrade

### ISSUE THREAD

**Issue by tamsky** [aws/amazon-managed-grafana-roadmap#71]
Upstream version 9.5.0 was first released on 2023-04-04 (357 days ago).
- https://github.com/grafana/grafana/blob/master/CHANGELOG.md#950-2023-04-04

Any roadmap/guidance regarding availability of the 9.5.x stream of releases would be appreciated.

**Comment by akiss-ic** [comment]
There are some major bug fixes beyond v9.4.7. It is a bit ridiculous how little support AWS is providing to this service in terms of offering updates. I can see having to delay major releases but point updates? Come on.

**Comment by VermaPriyanka** [comment]
https://github.com/aws/amazon-managed-grafana-roadmap/discussions/74
