### ISSUE TITLE
Quickwit support in AMG

### ISSUE THREAD

**Issue by jfreeland** [aws/amazon-managed-grafana-roadmap#78]
I'd like to use https://grafana.com/grafana/plugins/quickwit-quickwit-datasource/ in AMG.

**Comment by VermaPriyanka** [comment]
Quickwit is now available to install with [Plugin Management](https://docs.aws.amazon.com/grafana/latest/userguide/grafana-plugins.html) enabled, in Amazon Managed Grafana.
