### ISSUE TITLE
Support Alert Silence for the Grafana Alertmanager

### ISSUE THREAD

**Issue by Dragotic** [aws/amazon-managed-grafana-roadmap#82]
The OSS Grafana supports Silences for the default Grafana Alertmanager as stated in the [docs](https://grafana.com/docs/grafana/latest/alerting/configure-notifications/create-silence/).

However, the Amazon Grafana doesn't support this feature for the default Grafana Alertmanager but only for external Alertmanager as stated in the [AWS Docs](https://docs.aws.amazon.com/grafana/latest/userguide/v10-alerting-silences.html).
> For external Alert manager data sources (including Amazon Managed Service for Prometheus), you can suppress alert notifications with a silence.

Are there any plans to support this as it is the default behavior or was it removed on purpose?

**Comment by VermaPriyanka** [comment]
Silences support for Grafana Managed alerts is shipping shortly, along with the fix for duplicate notifications.

**Comment by Dragotic** [comment]
@VermaPriyanka Thank you for the reply. Could you be a bit more specific with regards to "shortly"? You have given the same "shortly" answer in the duplicate notifications issue and it's been over a month and still nothing was released

**Comment by VermaPriyanka** [comment]
Thanks for your patience. Notifications have been sent out to existing customers using Grafana alerts, about the release of this update. Will post an announcement here, once the update is worldwide.

**Comment by VermaPriyanka** [comment]
Amazon Managed Grafana now supports silences for Grafana alerts. See announcement [here](https://github.com/aws/amazon-managed-grafana-roadmap/discussions/85).
